"""Add soft delete

Revision ID: 08234bc40a2a
Revises: c70dd0cbc94a
Create Date: 2026-03-25 23:02:42.651584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08234bc40a2a'
down_revision: Union[str, None] = 'c70dd0cbc94a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('todo_items', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'deleted_at')
    op.drop_column('todo_items', 'is_deleted')
    # ### end Alembic commands ###
