"""add_scheduled_at_to_todo_items

Revision ID: 95c8c64987fd
Revises: 08234bc40a2a
Create Date: 2026-03-26 23:13:51.954980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '95c8c64987fd'
down_revision: Union[str, None] = '08234bc40a2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo_items', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo_items', 'scheduled_at')
    # ### end Alembic commands ###
