"""add_user_modules_table

Revision ID: b3c5320696bc
Revises: bfed11e6fa5b
Create Date: 2026-04-05 10:54:18.530459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b3c5320696bc'
down_revision: Union[str, None] = 'bfed11e6fa5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('user_modules',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('module_key', sa.String(length=32), nullable=False),
    sa.Column('granted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'module_key')
    )

    # 数据迁移：为所有非超管用户授予当前全部模块，保持向后兼容
    from datetime import datetime, timezone
    from app.core.modules import MODULES

    bind = op.get_bind()
    now = datetime.now(timezone.utc)
    users = bind.execute(sa.text(
        "SELECT id FROM users WHERE is_superuser = false OR is_superuser IS NULL"
    )).fetchall()
    rows = [
        {"user_id": u.id, "module_key": m["key"], "granted_at": now}
        for u in users
        for m in MODULES
    ]
    if rows:
        bind.execute(
            sa.text(
                "INSERT INTO user_modules (user_id, module_key, granted_at) "
                "VALUES (:user_id, :module_key, :granted_at)"
            ),
            rows,
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_modules')
    # ### end Alembic commands ###
