"""add_todo_comments_table

Revision ID: bfed11e6fa5b
Revises: b4e2f3a1c8d9
Create Date: 2026-04-03 18:36:36.859068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bfed11e6fa5b'
down_revision: Union[str, None] = 'b4e2f3a1c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('todo_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['todo_item_id'], ['todo_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_comments_todo_item_id'), 'todo_comments', ['todo_item_id'], unique=False)
    op.create_index(op.f('ix_todo_comments_user_id'), 'todo_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_comments_user_id'), table_name='todo_comments')
    op.drop_index(op.f('ix_todo_comments_todo_item_id'), table_name='todo_comments')
    op.drop_table('todo_comments')
    # ### end Alembic commands ###
